[package]
name = "cultural-credential-registry"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk.workspace = true
stellar-access.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-access.workspace = true
